name: Build cypress-ms-teams-reporter

on:
  push:
  pull_request:
    branches: [main]

env:
  MS_TEAMS_WEBHOOK_URL: ${{ secrets.MSTEAMS_WEBHOOK_URL }}
  ENV_SUT: ${{ secrets.ENV_SUT }}
  CI_PROVIDER_TO_TEST: "github"

defaults:
  run:
    working-directory: cypress-ms-teams-reporter

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: cypress-ms-teams-reporter/yarn.lock
      - run: yarn install
      - run: npm run lint
      - run: npm run compile
      - run: npm run test
      - run: npm test
      - run: make test
      - run: make combine-reports && make generate-report
      - name: get artifacts 1
        uses: actions/upload-artifact@v4
        with:
          name: test-output-1-${{matrix.node-version}}
          path: |
            cypress-ms-teams-reporter/cypress/reports
            cypress-ms-teams-reporter/cypress/videos
            cypress-ms-teams-reporter/cypress/screenshots
            cypress-ms-teams-reporter/mochareports
      - run: npm run ms-teams-ts
      - run: npm run ms-teams-js
      - run: npm run ms-teams-ts-opts
      - run: npm run ms-teams-js-opts
      - run: npm run ms-teams-js-opts-test-passed
      - run: npm run ms-teams-js-opts-test-failed
      - run: npm run ms-teams-js-opts-build-failed
      - run: npm run cli
      - name: get artifacts 2
        uses: actions/upload-artifact@v4
        with:
          name: test-output-2-${{matrix.node-version}}
          path: |
            cypress-ms-teams-reporter/src/ms-teams/test
            cypress-ms-teams-reporter/cypress/reports/mocha
